package com.hotelpayroll.entity;

public enum Permission {
    VIEW_ORDERS,
    UPDATE_ORDER_STATUS,
    VIEW_RESERVATIONS,
    UPDATE_RESERVATION_STATUS,
    ASSIGN_TABLES,
    MANAGE_TABLES,
    VIEW_MENU,
    VIEW_REPORTS,
    VIEW_LIVE_DINING,
    MANAGE_MENU,
    CANCEL_RESERVATIONS,
    CREATE_RESERVATIONS
}
